events:
  - event_art
  - event_athletics
  - event_career
  - event_dance
  - event_festival
  - event_fitness_wellness
  - event_food
  - event_free
  - event_fundraiser_vol
  - event_geek
  - event_kidfriendly
  - event_literary
  - event_music
  - event_outdoor
  - event_sale
  - event_singles

